config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :quantities
  root to: 'recipes#index'

  resources :categories
  resources :recipes
  resources :ingredients

end

app/models/ability.rb
class Ability
  include CanCan::Ability

    def initialize(user)
        user ||= User.new

        if user.role?(:admin)
            can :manage, :all
        else
            can :read, Recipe
        end
    end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :recipes
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :quantities
  has_many :recipes, through: :quantities
end

app/models/quantity.rb
class Quantity < ActiveRecord::Base
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :category

  has_many :quantities
  has_many :ingredients, through: :quantities
  mount_uploader :recipe_image, RecipeImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def role?(role_to_compare_to)
           role_to_compare_to.to_s == self.role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: "You can't access this page"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    Category.create(category_params) 
    redirect_to(categories_path)
  end

  def show
  end

  def destroy
    @category.destroy
    redirect_to(categories_path)
  end

  def edit
  end

  def update
    @category.update(category_params) 
    redirect_to(categories_path)
  end


  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end


end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    Ingredient.create(ingredient_params) 
    redirect_to(ingredients_path)
  end

  def show
  end

  def destroy
    @ingredient.destroy
    redirect_to(ingredients_path)
  end

  def edit
  end

  def update
    @ingredient.update(ingredient_params) 
    redirect_to(ingredients_path)
  end


  private

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end


end

app/controllers/quantities_controller.rb
class QuantitiesController < ApplicationController
  before_action :set_quantity, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  
  def index
    @quantities = Quantity.all
  end

  def show
  end

  def new
    @quantity = Quantity.new
  end

  def edit
  end

  def create
    Quantity.create(quantity_params) 
    redirect_to(quantities_path)
  end

  def update
    @quantity.update(quantity_params) 
    redirect_to(quantities_path)
  end

  def destroy
    @quantity.destroy
    redirect_to(quantities_path)
  end

  private
    def set_quantity
      @quantity = Quantity.find(params[:id])
    end

    def quantity_params
      params.require(:quantity).permit(:ingredient_id, :recipe_id, :quantity)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    Recipe.create(recipe_params)
    redirect_to(recipes_path)
  end

  def show
  end

  def destroy
    @recipe.destroy
    redirect_to(recipes_path)
  end

  def edit
  end

  def update
    @recipe.update(recipe_params) 
    redirect_to(recipes_path)
  end


  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    # allows these params to be accessed by the methods above
    params.require(:recipe).permit(:name, :recipe_image, :category_id, :instructions, {ingredient_ids: []})
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
<%= category.name %>
<%= link_to("Show #{category.name}", category_path(category)) %>
<%= button_to('Delete Category', category_path(category), method: :delete, data:{confirm: "Delete Category? Are you sure?"}) %>
<%= link_to("Edit Category", edit_category_path(category)) %>
<br>

app/views/categories/_form.html.erb
  <%= form_for @category do |f| %>
  <%= f.label :name, 'Category Name:' %>
  <%= f.text_field :name %>
  <br>
  <br>
  <%= f.submit button_text %>
<% end %>

app/views/categories/edit.html.erb
<%= render partial: "form", locals: { button_text: 'Update Category'} %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<%= render @categories %>
<br>
<div><%= link_to 'New Category', new_category_path %></div>

app/views/categories/new.html.erb
<%= render partial: "form", locals: { button_text: 'Create Category'} %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<p>
<h2><%= @category.name %></h2>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

<p>
  <strong>Recipes:</strong><br>
  <% @category.recipes.each do |recipe| %>
    <%= recipe.title %><br>
  <% end %>
</p>

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<p>
  <strong>Recipes:</strong><br>
  <% @ingredient.recipes.each do |recipe| %>
    <%= recipe.title %><br>
  <% end %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/layouts/_menu.html.erb
<p>
  <% if user_signed_in? %>
    <%= link_to 'logout', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to 'login', new_user_session_path %>
    <%= link_to 'register', new_user_registration_path %>
  <% end %>
</p>
  <div class="container">
  <div class="row">
    <div class="twelve columns">
      <nav>
        <ul>
          <li><a><%= link_to('Categories', categories_path) %></a></li>
          <li><a><%= link_to('Recipes', recipes_path) %></a></li>
          <li><a><%= link_to('Ingredients', ingredients_path) %></a></li>
          <li><a><%= link_to('Quantities', quantities_path) %></a></li>
        </ul>
      </nav>  
    </div> 
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav><h1>Cook Some Stuff</h1>

<%= render partial: "layouts/menu" %>
</nav>
<%= yield %>

</body>
</html>

app/views/quantities/_form.html.erb
  <%= form_for @quantity do |f| %>
  <%= f.label :ingredient_id %><br>
  <%= f.collection_select(:ingredient_id, Ingredient.all, :id, :name) %>
  <br>
  <%= f.label :recipe_id %><br>
  <%= f.collection_select(:recipe_id, Recipe.all, :id, :title) %>
  <br>
  <%= f.label :quantity %><br>
  <%= f.text_field :quantity %>
  <br>
  <br>
  <%= f.submit button_text %>
  <% end %>

app/views/quantities/_quantity.html.erb
<%= quantity.ingredient.try(:name) %>
<%= quantity.recipe.try(:name) %>
<%= quantity.quantity %>
<%= link_to 'Show', quantity %>
<%= button_to('Delete Quantity', quantity_path(quantity), method: :delete, data:{confirm: "Delete Quantity? Are you sure?"}) %>
<%= link_to("Edit Quantity", edit_quantity_path(quantity)) %>
<br>

app/views/quantities/edit.html.erb
<%= render partial: "form", locals: { button_text: 'Update Quantity'} %>

app/views/quantities/index.html.erb
<p id="notice"><%= notice %></p>
<%= render @quantities %>
<%= link_to 'New Quantity', new_quantity_path %>

app/views/quantities/new.html.erb
<%= render partial: "form", locals: { button_text: 'Create Quantity'} %>

app/views/quantities/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Ingredient:</strong>
  <%= @quantity.ingredient.try(:name) %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @quantity.recipe.try(:title) %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @quantity.quantity %>
</p>

<%= link_to 'Edit', edit_quantity_path(@quantity) %> |
<%= link_to 'Back', quantities_path %>

app/views/recipes/_form.html.erb
  <%= form_for @recipe do |f| %>
  <%= f.label :title, 'Recipe Title:' %>
  <%= f.text_field :title %>
  <br>
  <br>
  <%= f.label :instructions %>
  <%= f.text_field :instructions %>
  <br>
  <br>
  <%= f.label :category_id %>
  <%= f.select :category_id, Category.all.map { |c| [c.name, c.id] } %>
  <br>
  <br>
  <div class="field">
  <%= f.label :recipe_image %><br />
  <%= f.file_field :recipe_image %>    
  </div>
  <%= f.submit button_text %>
<% end %>

app/views/recipes/_recipe.html.erb
<nav class ="box">
  <ul>
    <li><%= recipe.title %></li>
    <li> <%= link_to image_tag(recipe.recipe_image.thumb.url), recipe.recipe_image.medium.url %></li>
    <li><%= link_to("Show #{recipe.title}", recipe_path(recipe)) %></li>
    <li><%= link_to("Edit Recipe", edit_recipe_path(recipe)) %></li>
    <li><%= button_to('Delete Recipe', recipe_path(recipe), method: :delete, data:{confirm: "Delete Them? Are you sure?"}) %></li>
    
  </ul>
</nav>

app/views/recipes/edit.html.erb
<%= render partial: "form", locals: { button_text: 'Update Recipe'} %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>
<%= render @recipes %>
<div class="nav"><%= link_to 'New Recipe', new_recipe_path %></div>

app/views/recipes/new.html.erb
<%= render partial: "form", locals: { button_text: 'Create Recipe'} %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @recipe.title %></h2>
<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>
  <br>
  <p>
    <strong>Category:</strong>
    <%= @recipe.category.try :name %>
  </p>
  <p>
    <b>Image:</b>
    <%= link_to image_tag(@recipe.recipe_image.thumb.url), @recipe.recipe_image.medium.url %>
  </p>
  <br>
  <p><%= @recipe.instructions %></p>
  <br>
  <p>
    <strong>Ingredients:</strong><br>
    <% @recipe.quantities.each do |quantity| %>
      <%= quantity.quantity %>
      <%= quantity.ingredient.try(:name) %><br>
    <% end %>
  </p>